# -*- coding: utf-8 -*-
"""Startup_MultiAgent_Project_Morooj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sU3n_kDx0JYTogcNYuNKPze9JUxC-RLG
"""

# 0) Install deps
!pip install -qU langchain-core==0.3.10 langchain-openai==0.2.6 tiktoken
!pip install -qU langchain langchain-core langchain-openai openai tiktoken

# 1) API key
import os, getpass
os.environ.pop("OPENAI_API_KEY", None)
os.environ["OPENAI_API_KEY"] = getpass.getpass("Enter your OpenAI API key: ").strip()

# 2) Imports
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

# 3) Base model
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.3)

# 4) User inputs (edit as you like)
user_ctx = {
    "sector": "HealthTech",
    "audience": "Adults with chronic conditions",
    "constraints": "Budget <= 20k, Launch in 3 months, KSA market",
    "market_note": "Telemedicine is growing; demand for personalized prevention and remote monitoring."
}

# 5) Prompts (Agents)

idea_prompt = PromptTemplate.from_template(
"""
You are an Idea Creator. Given:
- Sector: {sector}
- Target audience: {audience}
- Constraints: {constraints}

Generate 5 realistic startup ideas for this context.
For each idea provide:
- Name
- One-line value proposition
- Core features (3 bullets)
Keep it concise and business-ready.
"""
)

market_prompt = PromptTemplate.from_template(
"""
You are a Market Analyst. Analyze the following startup ideas for the KSA market.
Consider trends, target segments, competitors, risks, and opportunities.
Market note: {market_note}

Ideas:
{ideas}

Return a numbered list. For each idea provide:
- Market fit (short)
- Key opportunities (2 bullets)
- Key risks (2 bullets)
"""
)

feas_prompt = PromptTemplate.from_template(
"""
You are a Feasibility Expert. Evaluate each idea on:
- Technical feasibility
- Business feasibility (cost, GTM speed)
Score each on 1-10 and give a final combined score.
Be practical given: {constraints}

Ideas to evaluate:
{ideas_with_market}

Return a table-like text:
Idea N: Name
Tech: x/10, Biz: y/10, Final: z/10
1-2 lines rationale.
"""
)

pm_prompt = PromptTemplate.from_template(
"""
You are a Project Manager. Using feasibility scores and market notes, select the single best idea.
Explain why it wins in 3-4 bullet points.
Then provide a 4-week high-level execution plan (bulleted).
Input:
{feasibility_scores}
"""
)

pitch_prompt = PromptTemplate.from_template(
"""
You are a Pitch Writer. Write a concise investor-style pitch (150-200 words) for the selected idea.
Include: problem, solution, target user, differentiation, simple business model, and call to action.
Selected idea context:
{selected_idea}
"""
)

# 6) Chains
idea_chain = idea_prompt | llm | StrOutputParser()
market_chain = market_prompt | llm | StrOutputParser()
feas_chain = feas_prompt | llm | StrOutputParser()
pm_chain = pm_prompt | llm | StrOutputParser()
pitch_chain = pitch_prompt | llm | StrOutputParser()

# 7) Orchestration
def run_workflow(ctx):
    ideas = idea_chain.invoke(ctx)
    market = market_chain.invoke({"market_note": ctx["market_note"], "ideas": ideas})
    feas = feas_chain.invoke({"constraints": ctx["constraints"], "ideas_with_market": ideas + "\n\n" + market})
    pm = pm_chain.invoke({"feasibility_scores": feas})
    pitch = pitch_chain.invoke({"selected_idea": pm})

    return {
        "ideas": ideas,
        "market": market,
        "feasibility": feas,
        "pm_selection": pm,
        "pitch": pitch
    }

# 8) Execute
out = run_workflow(user_ctx)

# 9) Safe print helpers to avoid Unicode issues
def u(x): return str(x).encode("utf-8", "ignore").decode("utf-8")
def show(title, text):
    print(title)
    print(u(text))
    print("\n" + "="*60 + "\n")

show("=== Startup Ideas ===", out["ideas"])
show("=== Market Analysis ===", out["market"])
show("=== Feasibility Scores ===", out["feasibility"])
show("=== PM Selection & Plan ===", out["pm_selection"])
show("=== Investor-style Pitch ===", out["pitch"])

# 10) Save report
report = f"""
Sector: {user_ctx['sector']}
Audience: {user_ctx['audience']}
Constraints: {user_ctx['constraints']}

=== Startup Ideas ===
{out['ideas']}

=== Market Analysis ===
{out['market']}

=== Feasibility Scores ===
{out['feasibility']}

=== PM Selection & Plan ===
{out['pm_selection']}

=== Investor-style Pitch ===
{out['pitch']}
"""
with open("startup_multiactor_report.txt", "w", encoding="utf-8") as f:
    f.write(report)
print("Saved: startup_multiactor_report.txt")

"""## Reflection
During this AI Startup project, I learned how multiple AI agents can collaborate to complete a complex task step by step.
Each agent had a clear role — the Idea Creator generated realistic startup ideas, the Market Analyst evaluated market trends, the Feasibility Expert rated the practicality, and the Project Manager coordinated everything before the Pitch Writer summarized the final concept.

Through this workflow, I understood the importance of prompt design and how clear instructions can dramatically change AI results. It was also interesting to see how LangChain can simulate teamwork between agents, making the process feel more human-like.

The most valuable takeaway was realizing how AI can speed up brainstorming and early project planning. However, human judgment is still essential to verify ideas and adapt them to real-world situations. Overall, this project improved my understanding of AI collaboration, logical workflows, and creative automation.
"""